language: python
python:
  - "2.7"

addons:
  apt:
    packages:
    - sshpass
services:
  - docker

# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
# script:
# - python manage.py test vsc

before_install:
  - docker --version
  - docker-compose up -d
  - docker images
  - docker ps -a

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push $DOCKER_USERNAME/vsc_app:latest

